### ISSUE TITLE
Rules hang when upgrade

### ISSUE THREAD

**Issue by timatnuf** [objective-see/LuLu#71]
<img width="1012" alt="screen shot 2018-07-10 at 9 58 40 am" src="https://user-images.githubusercontent.com/27219412/42514616-d58ad160-8427-11e8-82d7-028c3d2aee1e.png">

**Comment by timatnuf** [comment]
This hang occurs when upgrading from a version prior to 0.9.5 (not sure which one).  At the time of the upgrade, LuLu was uninstalled.  An uninstall and reinstall made no difference.

**Comment by objective-see** [comment]
Thanks for reporting! 
This should be fixed now in the latest version: 0.9.6!

**Comment by timatnuf** [comment]
<img width="572" alt="screen shot 2018-07-10 at 11 06 53 am" src="https://user-images.githubusercontent.com/27219412/42519146-5e4b7230-8431-11e8-817e-cc0a9e012a08.png">

**Comment by pwardle** [comment]
can you
1. close LuLu (app/rule's window)
2. run in Terminal: `log stream | grep LuLu`
3. (re)open LuLu and attempt to view rules

...do you see any error msgs in the log output? 
or can you just email the log output to bugs@objective-see.com? 

thanks!

**Comment by mnerd** [comment]
No, I see nothing

—
pozdrawiam,
Robert Morusiewicz

**Comment by kopischke** [comment]
I hate to do +1’s, but I have to: seeing the exact same issue on a fresh install of LuLu 0.9.7 via `brew cask`. The initial rule set does not seem to ever load, logging last outputs ”Loading Preferences From User CFPrefsD For Search List”. 

<details>
<summary>Full output of <code>log stream | grep LuLu</code>:</summary>

```
2018-07-28 15:01:38.041449+0200 0xece123   Activity    0x800000000035a589   71525  LuLu Helper: (CoreFoundation) Loading Preferences From User CFPrefsD For Search List
2018-07-28 15:01:45.347089+0200 0xed23ce   Activity    0x800000000035b6f0   71614  LuLu: (CoreFoundation) Loading Preferences From System CFPrefsD For Search List
2018-07-28 15:01:45.347674+0200 0xed23ce   Activity    0x800000000035b6f1   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD For Search List
2018-07-28 15:01:45.353095+0200 0xed23ce   Default     0x0                  71614  LuLu: (Sentry) Sentry Started -- Version: 3.12.0
2018-07-28 15:01:45.358727+0200 0xed23ce   Default     0x0                  71614  LuLu: LuLu(71614): starting config/pref's app (args: (
    "/Applications/LuLu.app/Contents/MacOS/LuLu"
2018-07-28 15:01:45.387126+0200 0xed23ce   Activity    0x800000000035b6f2   71614  LuLu: (CoreFoundation) Loading Preferences From System CFPrefsD For Search List
2018-07-28 15:01:45.387201+0200 0xed23ce   Activity    0x800000000035b6f3   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD For Search List
2018-07-28 15:01:45.397970+0200 0xed23ce   Activity    0x800000000035b6f4   71614  LuLu: (CoreFoundation) Loading Preferences From System CFPrefsD For Search List
2018-07-28 15:01:45.398799+0200 0xed23ce   Activity    0x800000000035b6f5   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD
2018-07-28 15:01:45.491869+0200 0xed23ce   Default     0x0                  71614  LuLu: LuLu(71614): sending request, via XPC, to get rules (wait: 0)
2018-07-28 15:01:45.492151+0200 0xed23d4   Default     0x0                  71614  LuLu: LuLu(71614) ERROR: failed to execute 'getRules' method on launch daemon (error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.objective-see.lulu was invalidated." UserInfo={NSDebugDescription=The connection to service named com.objective-see.lulu was invalidated.})
2018-07-28 15:01:45.538897+0200 0xed23ce   Activity    0x800000000035b6f6   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD
2018-07-28 15:01:45.541589+0200 0xed23ce   Activity    0x800000000035b6f7   71614  LuLu: (CoreFoundation) Loading Preferences From System CFPrefsD For Search List
2018-07-28 15:01:45.541658+0200 0xed23ce   Activity    0x800000000035b6f8   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD For Search List
2018-07-28 15:01:45.542136+0200 0xed23ce   Activity    0x800000000035b6f9   71614  LuLu: (CoreFoundation) Loading Preferences From System CFPrefsD For Search List
2018-07-28 15:01:45.542187+0200 0xed23ce   Activity    0x800000000035b6fa   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD For Search List
2018-07-28 15:01:45.567891+0200 0xed23ce   Activity    0x800000000035b6fb   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.568320+0200 0xed23ce   Activity    0x800000000035b6fc   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.568968+0200 0xed23ce   Activity    0x800000000035b6fd   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.569096+0200 0xed23ce   Activity    0x800000000035b6fe   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.569194+0200 0xed23ce   Activity    0x800000000035b6ff   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.569288+0200 0xed23ce   Activity    0x800000000035b700   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.569455+0200 0xed23ce   Activity    0x800000000035b701   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.569567+0200 0xed23ce   Activity    0x800000000035b702   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.569756+0200 0xed23ce   Activity    0x800000000035b703   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.569846+0200 0xed23ce   Activity    0x800000000035b704   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.570136+0200 0xed23ce   Activity    0x800000000035b705   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD
2018-07-28 15:01:45.625811+0200 0xed23ce   Default     0x0                  71614  LuLu: LuLu(71614): main (rules/pref) app launched
2018-07-28 15:01:45.625937+0200 0xed23d3   Default     0x0                  71614  LuLu: LuLu(71614): looking for login item /Applications/LuLu.app/Contents/Library/LoginItems/LuLu Helper.app/Contents/MacOS/LuLu Helper
2018-07-28 15:01:45.629608+0200 0xed23d3   Default     0x0                  71614  LuLu: LuLu(71614): login item already running and 'shouldRestart' not set, so no need to start it
2018-07-28 15:01:45.872111+0200 0xed23ce   Activity    0x800000000035b706   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.875855+0200 0xed23ce   Activity    0x800000000035b707   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:45.876894+0200 0xed23ce   Activity    0x800000000035b708   71614  LuLu: (CoreFoundation) _CopyData
2018-07-28 15:01:47.187129+0200 0xed23ce   Activity    0x800000000035b709   71614  LuLu: (CoreFoundation) Loading Preferences From System CFPrefsD For Search List
2018-07-28 15:01:47.187218+0200 0xed23ce   Activity    0x800000000035b70a   71614  LuLu: (CoreFoundation) Loading Preferences From User CFPrefsD For Search List
```
</summary>

Running macOS 10.12 (aka _High Sierra_), German  locale, admin privilege level account.

**Comment by kopischke** [comment]
Addendum: maybe unrelated, but I get `INFO : KSCrash.m (339): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports` on every install and uninstall via `brew cask`.

**Comment by objective-see** [comment]
Thanks again for reporting this, and @kopischke for the log output :)

Can you try the latest version? https://github.com/objective-see/LuLu/releases/tag/0.9.8
...I fixed a bug related to the `getRules` method, which hopefully fixes this issue. 

Please note also the format of the rule's file changed, so a full uninstall/re-install will be required 

Thanks!

**Comment by hleconte** [comment]
Same issue with Mojave 10.14.2. Lulu 1.1.1  . 
Grrrr !

![capture d ecran 2019-01-08 a 08 51 57](https://user-images.githubusercontent.com/46477604/50817007-bcde1e80-1322-11e9-9ab4-bf09fd7a7c92.png)

**Comment by objective-see** [comment]
Just [released](https://github.com/objective-see/LuLu/releases/tag/v1.2.0) version 1.2.0. Hope this fixes this issues.

Please note though that the rule format changed from the betas (< `1.0.0`) to the release builds, and thus beta rulesets are incompatible. 

If you had/have a beta version installed, I'd recommend manually uninstalling that first.

**Comment by CR34L** [comment]
Problem persists in 1.2.0. Rule window is spinning and no application is blocked. After complete uninstall and reinstall problem still there. Is there any way to delete rules manually?

**Comment by CR34L** [comment]
Spinning rule issue may be due to this: there are no default rules available. Path "/Library/Objective-See/LuLu" is missing rules.plist file. Even after fresh install.

**Comment by jgoldhammer** [comment]
Same problem here... Any suggestion to fix this @objective-see ?

**Comment by llayl** [comment]
Same problem here, fresh install of 1.2.0. on mbp mojave stuck on loading

**Comment by objective-see** [comment]
Thanks for the feedback!
The `rules.plist` file should be created the first time LuLu is started (and contain some basic default system rules). 

To manually remove the rules file, you can delete the `/Library/Objective-See/LuLu/rules.plist` file.


On restart, the rule.plist file should be (re)created.

1. Can you confirm that is it `rules.plist` is (still) not created? 
2. If it does exist, can you attach it here? 
3. If you run `log show | grep LuLu | grep ERROR` from the terminal, do any LuLu error messages show up?

**Comment by CR34L** [comment]
There are no error log messages available. 

In `/Library/Objective-See/LuLu` is nothing except **LuLu.bundle** and **installedApps.xml**. Rules plist is still missing. Fresh installation on 2019er MacBookPro with out of the box Mojave 10.14.1. Are there any special disk permissions needed?

**Comment by objective-see** [comment]
Also can you confirm that the LuLu kernel extension is loaded? (From a terminal, run: `$ kextstat | grep com.objective-see.lulu`)

```$ kextstat | grep com.objective-see.lulu
  170    1 0xffffff7f84700000 0x6000     0x6000     com.objective-see.lulu (1.2.0) A0CA7ACB-C825-3172-8139-299CD928C0D4 <8 6 5 3 1>```

**Comment by jgoldhammer** [comment]
I also have only these 2 items in the /Library/Objective-See/LuLu folder:

drwxr-xr-x  3 root  wheel    96B Feb 20 23:17 LuLu.bundle
-rw-r--r--  1 root  wheel   391K Feb 20 23:18 installedApps.xml

Kernel extension is not loaded -> no output for this command. 
kextstat itself is returning a lot of modules, but com.objective-see.lulu is not there...

Reinstalling via brew does not work. Should we try a manual installation?

**Comment by CR34L** [comment]
Kext seems to be loaded.

Output for kextstat is: `168    1 0xffffff7f86174000 0x5000     0x5000     com.objective-see.lulu (1.2.0) 52D7B886-3FA5-3F57-85DE-F183D63B9DBE <8 6 5 3 1>`

**Comment by Fridus** [comment]
Same problem, after upgrade from v1.1.2 to v1.2.0.

![capture d ecran 2019-03-01 a 10 33 10](https://user-images.githubusercontent.com/3214565/53629275-74016280-3c0d-11e9-86a3-31d6315d54c3.png)

I tried to reame the file `/Library/Objective-See/LuLu/rules.plist` and reboot.
The file is not recreated and I can't add manually a rule :'(

**Comment by Fridus** [comment]
Fixed with this steps for me : 
- remove app (with `AppCleaner`)
- `sudo rm -rf /Library/Objective-See`
- uninstall with `LuLu Installer` (1.2.0)
- reboot
- install with `LuLu Installer` (1.2.0)
- reboot

So, previous rules are lost ...

**Comment by CR34L** [comment]
Fixing and reinstalling with AppCleaner or other stuff doesn't work. Kext is loaded but still missing rules. LuLu doesn't work. Is there any known workaround available?

**Comment by yoursdearboy** [comment]
I have the same error about failed execution of XPC method.
I suppose because `com.objective-see.lulu` fails to start up. After loading it's plist `/Library/LaunchDaemons/com.objective-see.lulu.plist` manually I have next errors:

```
2019-03-30 23:16:10.249189+0300 0x1c5d4    Activity    0x10ed0              3667   0    LuLu: (libsystem_info.dylib) Retrieve User by ID
2019-03-30 23:16:10.262229+0300 0x1c5d4    Default     0x0                  3667   0    LuLu: (Sentry) Sentry Started -- Version: 3.12.4
2019-03-30 23:16:10.266968+0300 0x1c5d4    Default     0x0                  3667   0    LuLu: LuLu(3667) ERROR: failed to create log file, /Library/Objective-See/LuLu/LuLu.log
2019-03-30 23:16:10.267414+0300 0x1c5d4    Default     0x0                  3667   0    LuLu: LuLu(3667) ERROR: failed to init logging
```

**Comment by yoursdearboy** [comment]
Now I have a problem with the kernel extension. Since it may be related to the issue, I post errors here

```
2019-03-30 21:38:47.538318+0000 0xd36c     Default     0x0                  0      0    kernel: (LuLu) LULU: in (IOUserClient) initWithTask
2019-03-31 00:38:47.538379+0300 0xd36c     Default     0x0                  2082   0    LuLu: LuLu(2082) ERROR: IOServiceOpen() failed with: 0xe00002c2
2019-03-30 21:38:47.538335+0000 0xd36c     Default     0x0                  0      0    kernel: (LuLu) LULU: in (IOUserClient) free
2019-03-31 00:38:47.538652+0300 0xd36c     Default     0x0                  2082   0    LuLu: LuLu(2082) ERROR: failed to connect to kext, com_objective_see_firewall
```

**Comment by cappellino** [comment]
I encountered this problem with MacOS Mojave 10.14.4, just after setting a rule as "temporary". Maybe the problem could be related to this.

**Comment by Namouk** [comment]
Bumping the topic since I'm encountering the same issue on mojave 10.4.4

missing /Library/Objective-See/LuLu/rules.plist

Tried uninstalling, restarting, reinstalling, not to avail.

**Comment by Xanarkan** [comment]
I just installed LuLu on my new MacBook Pro and I have the exact same problem.
macOS 10.14.5 (18F203) and LuLu 1.2.0

Just discovered this app and seems very promising, especially since other outbound firewall aren't free and this one seems to be well designed.

If I can help somehow don't hesitate.

**Comment by wx-Yao** [comment]
Bumping the topic as Mojave 10.4.5 also have this problem. I also clicked the "temporary" option when applying some rules as one of the fellows did. Then it keeps spinning after that.

**Comment by edwardair** [comment]
v1.2.0 loading rules +1, but if i manually open another 'LuLu' app, and it show 2 lulu processes(and 1 LuLu Helper) in 'Activity Monitor', then i can see the rules

**Comment by neoyoli** [comment]
Any update on the issue? I have the same one, and I see first it was reported more than a year ago. Is LuLu still in active development?

**Comment by kakadais** [comment]
I've 

> Fixed with this steps for me :
> 
> * remove app (with `AppCleaner`)
> * `sudo rm -rf /Library/Objective-See`
> * uninstall with `LuLu Installer` (1.2.0)
> * reboot
> * install with `LuLu Installer` (1.2.0)
> * reboot
> 
> So, previous rules are lost ...

I've solved this issue without re-install.
Just rm that plist and reboot solved everything. 

This is greate app, thanks.

**Comment by ilgor** [comment]
I had the same issue. I did the followings:
1) I deleted the app 
2) re-installed
3) restart needed so I restarted my computer
4) it asked me to 'Allow' in firewall, I did
And it worked!

**Comment by morsamatias** [comment]
I had the same problem and I did the same thing that @ilgor and it worked. Important, don't delete the app, run the Lulu installer.app it have an option to uninstall.

**Comment by CR34L** [comment]
Updating to 1.2.3 raises this issue again:
LuLu kext was loaded:  158    1 0xffffff7f841c3000 0x5000     0x5000     com.objective-see.lulu (1.2.3) 57842B9A-B805-3781-8D0B-05DEF9775578 <8 6 5 3 1>

LuLu Helper crashes with this: LuLu(1137) ERROR: failed to execute daemon XPC method '-[XPCDaemonClient getRules:]_block_invoke' (error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.objective-see.lulu was invalidated."

No rules, no preferences, not working anymore. Installing / Reinstalling / Cleaning doesnt solve this issue.

Any suggestions?

**Comment by gotexis** [comment]
+1 facing this problem  - first time user, fresh install

**Comment by bgildea** [comment]
Still happening. MacBook Pro (13-inch, 2020)

**Comment by yujinyuz** [comment]
Also facing after a fresh install. Rebooting seemed to fix things
